- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    hostgroup: test-20180725095832

  tasks:
    - name: Create Tower host group
      inventory: "MMB demo"
      name: "{{ hostgroup }}"
      tower_verify_ssl: no
      state: present
