- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    hostgroup_base_name: test-20180725095832

  tasks:
    - name: Create Tower host group - web tier
      tower_group:
        inventory: "EC2 KNF inventory"
        name: "{{ hostgroup_base_name }}-{{ item }}"
        instance_filters: "tag:hostgroup={{ hostgroup_base_name }}-{{ item }}"
        state: present
      with_items:
        - app
        - web
        - db
