- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    host-group: test-20180725095832

  tasks:
    - name: Create Tower host group
      inventory: "MMB demo"
      name: "{{ host-group }}"
      tower_verify_ssl: no
      state: present

