- hosts: all
  vars:
    dbServerIp: "172.31.16.248"
    dbUsername: "test"
    dbPassword: "redhat"

  tasks:
    - name: Deploy PHP application
      template:
        src: index.php.j2
        dest: /var/www/html/index.php
    - name: Configure DB IP address
      shell: sed -i "s/AAAAA-SERVER-NAME/$(cat /etc/elos-demo.conf)/g" /var/www/html/index.php
    - name: Start the Apache service
      service:
        name: httpd
        enabled: True
        state: started
    - name: Send final Slack notification
      slack:
        token: "xoxp-406252418640-407106802613-406253044192-004a304e692a80ba46b4ec6ffc349e78"
        msg: "*Your service is available on http://{{ ansible_default_ipv4.address }}*"

