- hosts: all
  gather_facts: False
  tasks:
    - name: Deploy MariaDB server
      yum:
        name: mariadb-server
        state: installed

    - name: Start and enable MariaDB service
      service:
        name: mariadb.service
        enabled: yes
        state: started
