- hosts: all
  tasks:
    - name: Deploy PHP application
      template:
        src: index.php.j2
        dest: /var/www/html/index.php
    - name: Start the Apache service
      service:
        name: httpd
        enabled: True
        state: started
