- hosts: all
  vars:
    dbServerIp: "172.31.16.248"
    dbUsername: "test"
    dbPassword: "redhat"

  tasks:
    - name: Deploy PHP application
      template:
        src: index.php.j2
        dest: /var/www/html/index.php
    - name: Configure DB IP address
      command: echo \'sed \"s\/AAAAA-SERVER-NAME\/$\(cat \/etc\/elos-demo.conf\)\/g\" \/var\/www\/html\/index.php\' > /tmp/test.txt
    - name: Start the Apache service
      service:
        name: httpd
        enabled: True
        state: started
