- hosts: all
  gather_facts: True
  tasks:
    - name: Copy test data to the target DB VM
      copy: 
        src: mysqlsampledatabase.sql
        dest: /root/mysqlsampledatabase.sql

    - name: Load test data to DB
      mysql_db:
        state: import
        name: all
        target: /root/mysqlsampledatabase.sql


