- hosts: all
  gather_facts: True
  tasks:
    - name: Copy test data to the target DB VM
      file: 
        src: mysqlsampledatabase.sql
        path: /root/mysqlsampledatabase.sql

    - name: Load test data to DB
      command: /bin/mysql < mysqlsampledb.sql


