- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Provision instances
      ec2:
        key_name: KNF-shared-key
        group: mmb-demo
        instance_type: t2.micro
        image: ami-7c491f05
        wait: true
        exact_count: 2
        count_tag:
          Name: "{{ hostgroup_base_name }}_{{ item }}"
        instance_tags:
          Name: "{{ hostgroup_base_name }}_{{ item }}"
          hostgroup: "{{ hostgroup_base_name }}_{{ item }}"
        region: eu-west-1
        vpc_subnet_id: subnet-35739343
      tags:
        - provision
      register: "{{ item }}_vms"
      with_items:
        - web
        - db

    - name: Provision instances
      ec2:
        key_name: KNF-shared-key
        group: mmb-demo
        instance_type: t2.micro
        image: ami-7c491f05
        wait: true
        exact_count: 1
        count_tag:
          Name: "{{ hostgroup_base_name }}_{{ item }}"
        instance_tags:
          Name: "{{ hostgroup_base_name }}_{{ item }}"
          hostgroup: "{{ hostgroup_base_name }}_{{ item }}"
        region: eu-west-1
        vpc_subnet_id: subnet-35739343
      tags:
        - provision
      register: "{{ item }}_vms"
      with_items:
        - db
