- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Provision a set of instances
      ec2:
         key_name: KNF-shared-key
         group: mmb-demo
         instance_type: t2.micro
         image: ami-7c491f05
         wait: true
         exact_count: 3
         count_tag:
            Name: Demo
         instance_tags:
            Name: Demo
         region: eu-west-1
      register: ec2

   - name: Add all instance public IPs to host group
     add_host: hostname={{ item.public_ip }} groups=mmb-provisioned
     loop: "{{ ec2.instances }}"

